from sys import argv
from re import sub, finditer, VERBOSE
f1=open(argv[2], 'w+')

def gen(defs):
    indent = 0
    enum = False
    def p(s): print(" " * (indent * 4) + s, file=f1)
    for item in finditer("""
        (?P<type> message|enum) \\s+ (?P<name> \\w+) \\s* \\{ |
        (?P<var> \\w+) \\s* = \\s* (?P<val> \\w+) \\s* ; |
        \\}
        """, defs, flags=VERBOSE):
        if item.group(0) == "}":
            indent = indent - 1
            p("};" if enum else "}")
            enum = False;
        elif item.group('type') == 'enum':
            p("enum class %s {" % item.group('name'))
            indent = indent + 1
            enum = True
        elif item.group('type') == 'message':
            p("namespace %s {" % item.group('name'))
            indent = indent + 1
            enum = False
        else:
            if enum:
                p("%s = %s," % (item.group('var'), item.group('val')))

print("// Auto-generated by reql/gen.py", file=f1)
print("#pragma once", file=f1)
print("namespace RethinkDB { namespace Protocol {", file=f1)
gen(sub("//.*", "", open(argv[1]).read()))
print("} }", file=f1)
f1.close()
